# Generated by Django 5.1.4 on 2025-01-05 21:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 5), ('tea_in_uk', 9), ('most_famous_teas', 15), ('how_to_brew', 18), ('favorite_teas', 21), ('rich_text', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hero naslov', 'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Opis hero sekcije', 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Tekst na dugmetu', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link za dugme', 'required': True}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Pozadinska slika', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('button_text', 2), ('button_link', 3), ('background_image', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Naslov sekcije', 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Opis sekcije', 'required': True}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Slika za sekciju', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7), ('image', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Naziv čaja', 'required': True}), 11: ('wagtail.blocks.TextBlock', (), {'help_text': 'Opis čaja', 'required': True}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Slika čaja', 'required': True}), 13: ('wagtail.blocks.StructBlock', [[('name', 10), ('description', 11), ('image', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {}), 15: ('wagtail.blocks.StructBlock', [[('title', 6), ('teas', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Korak za pripremu čaja', 'required': True}), 17: ('wagtail.blocks.ListBlock', (16,), {}), 18: ('wagtail.blocks.StructBlock', [[('title', 6), ('steps', 17)]], {}), 19: ('wagtail.blocks.TextBlock', (), {'help_text': 'Poziv za korisnike da podele svoje omiljene čajeve', 'required': True}), 20: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL za slanje podataka formulara', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 19), ('form_action', 20)]], {}), 22: ('wagtail.blocks.RichTextBlock', (), {})}, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='navigation',
            field=wagtail.fields.StreamField([('navigation', 7)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'required': True}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.BooleanBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 1), ('url', 2), ('page', 3), ('open_in_new_tab', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('logo', 0), ('links', 6)]], {})}, null=True),
        ),
    ]
