# Generated by Django 5.1.4 on 2025-01-04 19:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='navigation',
            field=wagtail.fields.StreamField([('navigation', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Unesite naslov linka', 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': 'Unesite URL', 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Izaberite stranicu', 'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Otvori u novom tabu', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('url', 1), ('page', 2), ('open_in_new_tab', 3)]], {})}, null=True),
        ),
    ]
