# Generated by Django 5.1.4 on 2025-01-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_homepage_body_homepage_navigation"),
        ("home", "0006_alter_homepage_body_alter_homepage_navigation"),
    ]

    operations = []
