# Generated by Django 5.1.4 on 2025-01-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20250106_1216'),
        ('home', '0008_alter_homepage_body'),
    ]

    operations = [
    ]
