# Generated by Django 5.1.4 on 2025-01-07 13:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20250107_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 5), ('tea_in_uk', 10), ('most_famous_teas', 17), ('how_to_brew', 25), ('favorite_teas', 26)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Hero image', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hero title', 'required': True}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Description', 'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button title', 'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Button Link', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('description', 2), ('button_text', 3), ('button_link', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Title', 'required': True}), 7: ('wagtail.blocks.TextBlock', (), {'help_text': 'Description', 'required': True}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card Title', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'help_text': 'Card Description', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7), ('fun_fact', 8), ('fun_fact_description', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Naslov sekcije', 'required': True}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Slika čaja', 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Naziv čaja', 'required': True}), 14: ('wagtail.blocks.TextBlock', (), {'help_text': 'Opis čaja', 'required': True}), 15: ('wagtail.blocks.StructBlock', [[('image', 12), ('name', 13), ('description', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('title', 11), ('teas', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Card title', 'required': True}), 20: ('wagtail.blocks.TextBlock', (), {'help_text': 'Card Description', 'required': True}), 21: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button title', 'required': True}), 22: ('wagtail.blocks.TextBlock', (), {'help_text': 'Tip Description', 'required': True}), 23: ('wagtail.blocks.StructBlock', [[('card_title', 19), ('card_description', 20), ('tip_button', 21), ('tip_description', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {}), 25: ('wagtail.blocks.StructBlock', [[('title', 18), ('steps', 24)]], {}), 26: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7), ('image', 0)]], {})}, null=True),
        ),
    ]
